services:
  api:
    build: 
      context: ./api
      args:
        PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    container_name: organizasoft-api-container
    env_file:
      - .env
    volumes:
      - ./api:/api
    command: sh -c "npm install && npm run migrate:deploy && npm run seed && npm run dev"

  vue:
    build:
      context: ./vue
      args:
        VITE_BASE_URL_BACKEND: ${VITE_BASE_URL_BACKEND}
    container_name: organizasoft-front-container
    volumes:
      - ./vue:/vue
    ports:
      - "${FRONT_PORT}:80"
    depends_on:
      - api
    env_file:
      - .env