import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faUser,
  faFileLines,
  faClock,
  faLocationCrosshairs,
  faListCheck,
  faGears,
  faChartPie,
  faLocationDot,
  faRightFromBracket,
  faThumbTack,
  faTrash,
  faEdit,
  faMartiniGlassCitrus,
  faCircleNotch,
  faRedo,
} from "@fortawesome/free-solid-svg-icons";
library.add(
  faUser,
  faThumbTack,
  faListCheck,
  faFileLines,
  faClock,
  faLocationCrosshairs,
  faGears,
  faChartPie,
  faLocationDot,
  faRightFromBracket,
  faTrash,
  faEdit,
  faMartiniGlassCitrus,
  faCircleNotch,
  faRedo
);
