export type IAbility =
  | "all"
  | "criar"
  | "visualizar"
  | "atualizar"
  | "deletar"
  | "detalhar"
  | "exportar"
  | "efetivar"
  | "estornar"
  | "importar"
  | "transferir"
  | "criar_pix"
  | "criar_venda_pdv"
  | "criar_checkout";
export type IEntity =
  | "usuarios"
  | "clientes"
  | "produtos"
  | "vendas"
  | "lancamentos"
  | "categorias_lancamentos"
  | "categorias_produtos"
  | "contas_lancamentos"
