services:
  app:
    build: .
    ports:
      - "3340:5000"
    env_file:
      - .env_prod
    volumes:
      - .:/app
    command: sh -c "npm install && npm run migrate:deploy && npm run seed && npm run dev"
    stdin_open: true 
    tty: true 
